// flow-typed signature: 99e9ae745790b648f5609a1fc3745725
// flow-typed version: <<STUB>>/bourbon_v4.3.4/flow_v0.63.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'bourbon'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'bourbon' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'bourbon/eyeglass-exports' {
  declare module.exports: any;
}

// Filename aliases
declare module 'bourbon/eyeglass-exports.js' {
  declare module.exports: $Exports<'bourbon/eyeglass-exports'>;
}
declare module 'bourbon/index' {
  declare module.exports: $Exports<'bourbon'>;
}
declare module 'bourbon/index.js' {
  declare module.exports: $Exports<'bourbon'>;
}
