// flow-typed signature: 2aa2c2a7efb9aa3d2038b85435dc329d
// flow-typed version: <<STUB>>/font-awesome_v4.7.0/flow_v0.63.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'font-awesome'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'font-awesome' {
  declare module.exports: any;
}
