// flow-typed signature: a57d1df2a733e497ea57ab3d8287706d
// flow-typed version: <<STUB>>/grpc_v1.1.2/flow_v0.37.4

/**
 * This is an autogenerated libdef stub for:
 *
 *   'grpc'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'grpc' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'grpc/src/node/index' {
  declare module.exports: any;
}

declare module 'grpc/src/node/src/client' {
  declare module.exports: any;
}

declare module 'grpc/src/node/src/common' {
  declare module.exports: any;
}

declare module 'grpc/src/node/src/credentials' {
  declare module.exports: any;
}

declare module 'grpc/src/node/src/grpc_extension' {
  declare module.exports: any;
}

declare module 'grpc/src/node/src/metadata' {
  declare module.exports: any;
}

declare module 'grpc/src/node/src/server' {
  declare module.exports: any;
}

// Filename aliases
declare module 'grpc/src/node/index.js' {
  declare module.exports: $Exports<'grpc/src/node/index'>;
}
declare module 'grpc/src/node/src/client.js' {
  declare module.exports: $Exports<'grpc/src/node/src/client'>;
}
declare module 'grpc/src/node/src/common.js' {
  declare module.exports: $Exports<'grpc/src/node/src/common'>;
}
declare module 'grpc/src/node/src/credentials.js' {
  declare module.exports: $Exports<'grpc/src/node/src/credentials'>;
}
declare module 'grpc/src/node/src/grpc_extension.js' {
  declare module.exports: $Exports<'grpc/src/node/src/grpc_extension'>;
}
declare module 'grpc/src/node/src/metadata.js' {
  declare module.exports: $Exports<'grpc/src/node/src/metadata'>;
}
declare module 'grpc/src/node/src/server.js' {
  declare module.exports: $Exports<'grpc/src/node/src/server'>;
}
