// flow-typed signature: 1564f2b14eec94e904a59f95eae9a5ec
// flow-typed version: <<STUB>>/grpc-tools_v1.2.0-pre1/flow_v0.37.4

/**
 * This is an autogenerated libdef stub for:
 *
 *   'grpc-tools'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'grpc-tools' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'grpc-tools/bin/protoc_plugin' {
  declare module.exports: any;
}

declare module 'grpc-tools/bin/protoc' {
  declare module.exports: any;
}

// Filename aliases
declare module 'grpc-tools/bin/protoc_plugin.js' {
  declare module.exports: $Exports<'grpc-tools/bin/protoc_plugin'>;
}
declare module 'grpc-tools/bin/protoc.js' {
  declare module.exports: $Exports<'grpc-tools/bin/protoc'>;
}
declare module 'grpc-tools/index' {
  declare module.exports: $Exports<'grpc-tools'>;
}
declare module 'grpc-tools/index.js' {
  declare module.exports: $Exports<'grpc-tools'>;
}
